In [2]:
import numpy as np
import math
from itertools import groupby
from functools import partial

def make_twiddle(n1, n2):
    def w(k, n):
        return np.exp(2j * np.pi * k / n)

    I1 = np.arange(n1)
    I2 = np.arange(n2)
    return w(I1[:,None] * I2[None,:], n1*n2).astype('complex64')

## Radix-n data streamlining

For a radix-2 FFT, it is possible to divide input data in such a way that every butterfly operation reads and writes to two different arrays in memory. This could be advantageous for an implementation on the FPGA. The trick is to separate data locations based on the parity of their index.

### Parity

The index of each element in the array can be written in binary. In the case of a radix-2 FFT, we can see the array being reshaped in a $[2, 2, 2, \dots]$ shape. Every stage of the $n=2^k$ sized radix-2 FFT is being performed in a different dimension of the $k$-dimensional reshaped array. The indexing in this multi-dimensional array is the same as the binary notation for the linear index. That means that each time the 2-FFT is performed, the multi-index of the elements involved will differ by one bit in the linear index. Separating the array based on the parity of the index will guarantee that each 2-FFT operation reads and writes one (complex) number from each set. The parity is the sum of all the individual bits, modulo 2.

$$P_2(i) = \left(\sum_k b_k\right) \mod 2,\quad {\rm where}\, i := \sum_k b_k 2^k$$

We can extend this concept to the radix-4 FFT, on 4 data channels.

### 4-parity

In the radix-4 FFT we can view the array as being reshaped to a $[4, 4, 4, \dots]$ shape. The multi-index into this array is equivalent to the quarternary number notation of the linear index. Similar to the radix-2 parity, we can define the radix-4 parity as the sum of each quarternary digit in the index, modulo 4.

$$P_4(i) = \left(\sum_k q_k\right) \mod 4,\quad {\rm where}\, i := \sum_k q_k 4^k$$

This would ensure that each 4-FFT reads its data from the 4 different input channels. We define the `parity` function to work with any radix:

In [3]:
def digits(n, i):
    """Generates the n-numbered digits of i, in reverse order."""
    while True:
        if i == 0:
            return
        else:
            i, q = divmod(i, n)
            yield q
            
def parity(n, i):
    return sum(digits(n, i)) % n

To see which index belongs in which channel, we use a `groupby` on keyed the `parity` function

In [4]:
def channels(N, radix):
    parity_r = partial(parity, radix)
    return groupby(sorted(range(N), key=parity_r), parity_r)

for instance, for radix-2, size 16, this creates the following channels

In [5]:
for (g, i) in channels(16, 2):
    print(g, list(i))

0 [0, 3, 5, 6, 9, 10, 12, 15]
1 [1, 2, 4, 7, 8, 11, 13, 14]


### Example: radix-2 16-FFT

We can implement the 16-FFT as a radix-2 operation on an array of shape $[2,2,2,2]$.

In [6]:
def fft2(x0, x1):
    y = np.zeros(shape=(2,)+x0.shape, dtype='complex64')
    y[0] = x0 + x1
    y[1] = x0 - x1
    x0[:] = y[0]
    x1[:] = y[1]

To check whether our grouping works, we create a dummy array, and a dummy `fft2_check` that just checks if all arguments are in different channels.

In [7]:
def fft2_check(x0, x1):
    assert np.all(x0 != x1)

In [8]:
x = np.zeros(shape=(16,), dtype=int)
for (g, i) in channels(16, 2):
    x[list(i)] = g

In [9]:
N = 16
radix = 2

factors = [radix] * int(math.log(N, radix))
s = x.reshape(factors).transpose()

try:
    for k in range(len(factors)):
        fft2_check(np.take(s, 0, axis=k), np.take(s, 1, axis=k))
except AssertionError:
    print("failed")
else:
    print("succeeded")

succeeded


In [10]:
# x = (np.random.normal(size=N) + 1j * np.random.normal(size=N)).astype('complex64')
x = np.arange(0, N, dtype='complex64')
s = x.copy().reshape(factors).transpose()

fft2(s[...,0], s[...,1])

for k in range(1, len(factors)):
    w = make_twiddle(2, 2**k).conj()[:,:]
    z = s.reshape([-1, 2, 2**k])
    z *= w
    fft2(z[..., 0, :], z[..., 1, :])
    s = z

In [11]:
s.flatten()

array([120.        +0.j       ,  -7.9999995+40.21872j  ,
        -8.       +19.31371j  ,  -8.       +11.972846j ,
        -8.        +8.j       ,  -8.        +5.3454294j,
        -8.        +3.3137083j,  -8.        +1.591299j ,
        -8.        +0.j       ,  -8.        -1.591299j ,
        -8.        -3.3137083j,  -8.        -5.3454294j,
        -8.        -8.j       ,  -8.       -11.972846j ,
        -8.       -19.31371j  ,  -7.9999995-40.21872j  ], dtype=complex64)

In [12]:
abs(s.flatten() - np.fft.fft(x)).max()

3.577337255373132e-06

### Example: radix-4 64-FFT

In [13]:
for g, i in channels(64, 4):
    print(g, list(i))

0 [0, 7, 10, 13, 19, 22, 25, 28, 34, 37, 40, 47, 49, 52, 59, 62]
1 [1, 4, 11, 14, 16, 23, 26, 29, 35, 38, 41, 44, 50, 53, 56, 63]
2 [2, 5, 8, 15, 17, 20, 27, 30, 32, 39, 42, 45, 51, 54, 57, 60]
3 [3, 6, 9, 12, 18, 21, 24, 31, 33, 36, 43, 46, 48, 55, 58, 61]


In [14]:
from itertools import combinations
import math

def fft4_check(x0, x1, x2, x3):
    for (a, b) in combinations([x0, x1, x2, x3], 2):
        assert np.all(a != b)

In [15]:
N = 64
radix = 4

x = np.zeros(shape=(N,), dtype=int)
for g, i in channels(N, radix):
    x[list(i)] = g

In [16]:
factors = [radix] * int(math.log(N, radix))
s = x.reshape(factors)

try:
    for k in range(len(factors)):
        fft4_check(*(np.take(s, i, axis=k) for i in range(radix)))
except AssertionError:
    print("failed")
else:
    print("succeeded")

succeeded


## Implementing the radix-4 FFT

In [17]:
def fft4(x0, x1, x2, x3, w0=1, w1=1, w2=1, w3=1):
    a = w0*x0 + w2*x2
    b = w1*x1 + w3*x3
    c = w0*x0 - w2*x2
    d = w1*x1 - w3*x3
    x0[:] = a + b
    x1[:] = c - 1j*d
    x2[:] = a - b
    x3[:] = c + 1j*d

In [18]:
x = np.arange(0, N, dtype='complex64')
s = x.copy().reshape(factors).transpose()

fft4(*(s[...,k] for k in range(4)))

for k in range(1, len(factors)):
    w = make_twiddle(4, 4**k).conj()[:,:]
    z = s.reshape([-1, 4, 4**k])
    z *= w
    fft4(*(z[..., l, :] for l in range(4)))
    s = z

In [19]:
abs(s.flatten() - np.fft.fft(x)).max()

2.5034746158780763e-05

## OpenCL

Each of the transforms are in-place, meaning we can do this in any order, but we don't know the system in the indices yet.

In [20]:
# Fill `x` with the integer id of the array to which the location belongs
x = np.zeros(shape=(N,), dtype=int)
for g, i in channels(N, radix):
    x[list(i)] = g  # np.arange(N//radix, dtype=int)
s = x.reshape(factors).transpose()

perm = np.array([s[...,k].flatten() for k in range(4)])
perm

array([[0, 1, 2, 3, 1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2],
       [1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2, 0, 1, 2, 3],
       [2, 3, 0, 1, 3, 0, 1, 2, 0, 1, 2, 3, 1, 2, 3, 0],
       [3, 0, 1, 2, 0, 1, 2, 3, 1, 2, 3, 0, 2, 3, 0, 1]])

This pattern is the same for each iteration. Note that the permutation is always the same cycle starting at a different number. This means the top row gives us which of the four permutations is needed. Do we implement four different versions of `fft4` to implement each permutation?

In [21]:
colid = np.argsort(perm[0]).reshape(4,4)
colid

array([[ 0,  7, 10, 13],
       [ 1,  4, 11, 14],
       [ 2,  5,  8, 15],
       [ 3,  6,  9, 12]])

These are the indices into the index array that will select which of the four permutated versions of `fft4` needs to be used.

Now for the indices into each channel:

In [22]:
# Here `x` is the index into each source array
x = np.zeros(shape=(N,), dtype=int)
for g, i in channels(N, radix):
    #x[list(i)] = g  # np.arange(N//radix, dtype=int)
    x[list(i)] = np.arange(N//radix, dtype=int)
s = x.reshape(factors).transpose()

idx = np.array([s[...,k].flatten() for k in range(4)])
idx

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]])

So the first permutation is called with these indices

In [23]:
idx[:,colid[0]]

array([[ 0,  3,  2,  1],
       [ 4,  7,  6,  5],
       [ 8, 11, 10,  9],
       [12, 15, 14, 13]])

and so on ..., these all contain the same columns in different order. Meaning we can run each `fft4` permutation **with the same indices!**

In [24]:
z = s.reshape([-1, 4, 4])
idx = np.array([z[:,l,:].flatten() for l in range(4)])
idx

array([[ 0,  4,  8, 12,  0,  4,  8, 12,  0,  4,  8, 12,  0,  4,  8, 12],
       [ 1,  5,  9, 13,  1,  5,  9, 13,  1,  5,  9, 13,  1,  5,  9, 13],
       [ 2,  6, 10, 14,  2,  6, 10, 14,  2,  6, 10, 14,  2,  6, 10, 14],
       [ 3,  7, 11, 15,  3,  7, 11, 15,  3,  7, 11, 15,  3,  7, 11, 15]])

In [25]:
idx[:,colid[0]]

array([[ 0, 12,  8,  4],
       [ 1, 13,  9,  5],
       [ 2, 14, 10,  6],
       [ 3, 15, 11,  7]])

In [26]:
z = s.reshape([-1, 4, 16])
idx = np.array([z[:,l,:].flatten() for l in range(4)])

In [27]:
idx[:,colid[0]]

array([[ 0, 13, 10,  7],
       [ 0, 13, 10,  7],
       [ 0, 13, 10,  7],
       [ 0, 13, 10,  7]])

Only the last instance is different. However, note that these are the same indices as we found in computing the 4-parity.

# An algorithm by recipe

In [28]:
from dataclasses import dataclass

@dataclass
class MultiChannel:
    N: int
    radix: int
    
    @property
    def depth(self):
        return int(math.log(self.N, self.radix))
    
    @property
    def M(self):
        return self.N//self.radix
    
    @property
    def L(self):
        return self.M//self.radix
    
    @property
    def factors(self):
        return [self.radix] * self.depth
    
    @property
    def channels(self):
        return channels(self.N, self.radix)
    
    @property
    def channel_loc(self):
        x = np.zeros(shape=(self.N,), dtype=int)
        for g, i in self.channels:
            x[list(i)] = g
        return x.reshape(self.factors)
    
    @property
    def index_loc(self):
        x = np.zeros(shape=(self.N,), dtype=int)
        for g, i in self.channels:
            x[list(i)] = np.arange(self.M, dtype=int)
        return x.reshape(self.factors)
    
    def mix(self, x):
        return tuple(x[list(i)].copy() for g, i in self.channels)

    def unmix(self, s):
        x = np.zeros(shape=(self.N,), dtype='complex64')
        for g, i in self.channels:
            x[list(i)] = s[g]
        return x

In [29]:
def fft4x(x0, x1, x2, x3, i0, i1, i2, i3, w0=1, w1=1, w2=1, w3=1):
    a = w0*x0[i0] + w2*x2[i2]
    b = w1*x1[i1] + w3*x3[i3]
    c = w0*x0[i0] - w2*x2[i2]
    d = w1*x1[i1] - w3*x3[i3]
    x0[i0] = a + b
    x1[i1] = c - 1j*d
    x2[i2] = a - b
    x3[i3] = c + 1j*d

In [30]:
mc = MultiChannel(64, 4)

# let x be the input array
x = np.arange(0, N, dtype='complex64')

# <lin> ===========================================
s_lin = x.copy().reshape(mc.factors).transpose()
fft4(*(s_lin[...,k] for k in range(4)))
# </lin> ==========================================

mc =  MultiChannel(N=64, radix=4)

x = np.arange(N, dtype='complex64')
s = mc.mix(x.reshape(mc.factors).transpose().flatten())
    
# 16 fft-4, the inner-loop is best left unfolded
ca = mc.channel_loc.reshape([-1, 4])
ia = mc.index_loc.reshape([-1, 4])

for c, i in zip(ca, ia):
    fft4x(*[s[i] for i in c], *i)

assert abs(mc.unmix(s) - s_lin.flatten()).max() < 1e-4

In [31]:
# <lin> ===========================================
w = make_twiddle(4, 4).conj()
s_lin *= w
fft4(*(s_lin[..., l, :] for l in range(4)))
# </lin> ==========================================

ca = mc.channel_loc.transpose([0,2,1]).reshape([-1, 4])
ia = mc.index_loc.transpose([0,2,1]).reshape([-1, 4])
w_4_4 = (np.ones(shape=[4,4,4]) * w).transpose([0,2,1]).reshape([-1,4])

for c, i, w in zip(ca, ia, w_4_4):
    fft4x(*[s[i] for i in c], *i, *w)

assert abs(mc.unmix(s) - s_lin.flatten()).max() < 1e-4

In [32]:
# <lin> ===========================================
w = make_twiddle(4, 16).conj()
s_lin *= w.reshape([4,4,4])
fft4(*(s_lin[l] for l in range(4)))
# </lin> ==========================================

In [33]:
ca = mc.channel_loc.transpose([1,2,0]).reshape([-1, 4])
ia = mc.index_loc.transpose([1,2,0]).reshape([-1, 4])
w_4_16 = w.reshape([4,4,4]).transpose([1,2,0]).reshape([-1,4])

for c, i, w in zip(ca, ia, w_4_16):
    fft4x(*[s[i] for i in c], *i, *w)

assert abs(mc.unmix(s) - s_lin.flatten()).max() < 1e-4
assert abs(mc.unmix(s) - np.fft.fft(x)).max() < 1e-4

## Observations

The `ca` array is always the same.

# Unrolling the recipe for permutations

The pattern of the permutation shifts one every outer loop. To correct for this we need to permute all input factors

In [34]:
ca = mc.channel_loc.reshape([4, 4, 4])
perm = (ca[:,0,:].argsort(axis=1) + (np.arange(4)*4)[:,None]).flatten()

In [35]:
perm

array([ 0,  1,  2,  3,  7,  4,  5,  6, 10, 11,  8,  9, 13, 14, 15, 12])

In [36]:
[[i*4 + (rot-i)%4 for rot in range(4)] for i in range(4)]

[[0, 1, 2, 3], [7, 4, 5, 6], [10, 11, 8, 9], [13, 14, 15, 12]]

In [37]:
mc =  MultiChannel(N=64, radix=4)

x = np.arange(N, dtype='complex64')
s = mc.mix(x.reshape(mc.factors).transpose().flatten())
w_0 = np.ones(shape=[16,4])

w = make_twiddle(4, 4).conj()
w_4_4 = (np.ones(shape=[4,4,4]) * w).transpose([0,2,1]).reshape([-1,4])[perm]

w = make_twiddle(4, 16).conj()
w_4_16 = w.reshape([4,4,4]).transpose([1,2,0]).reshape([-1,4])[perm]

W = np.r_[w_0, w_4_4, w_4_16]

fa = 1
fb = 1
fc = 4
Wp = 0

for k in range(3):
    for i in range(4):
        for rot in range(4):
            ix = [fa * (i*4 + (rot - i)%4) + (1-fa) * (i*fc + j*fb) for j in range(4)]
            fft4x(*[s[(rot+j) % 4] for j in range(4)],
                  *ix,
                  *W[Wp])
            Wp += 1
    if fa == 0:
        fc //= 4
        fb *= 4
    else:
        fa = 0

In [38]:
assert abs(mc.unmix(s) - np.fft.fft(x)).max() < 1e-4

In [207]:
mc =  MultiChannel(N=1024, radix=4)
# perm = [i*mc.radix + (rot-i)%mc.radix for i in range(mc.L) for rot in range(mc.radix)]

ca = mc.channel_loc.reshape(mc.factors)
# perm = (ca[...,0,:].argsort(axis=1) + (np.arange(16)*4)[:,None]).flatten()

In [211]:
# 256
# perm = (ca[...,0,:].argsort(axis=-1) + (np.arange(16).reshape([4,4])*4)[...,None]).flatten()
# 1024
perm = (ca[...,0,:].argsort(axis=-1) + (np.arange(64).reshape([4,4,4])*4)[...,None]).flatten()

In [216]:
# x = np.arange(mc.N, dtype='complex64')
x = np.random.normal(size=mc.N) + 1j*np.random.normal(size=mc.N)
s = mc.mix(x.reshape(mc.factors).transpose().flatten())
W = np.ones(shape=[mc.M,4])

n = mc.radix
for k in range(mc.depth - 1):
    w = make_twiddle(4, n).conj()
    w_4_x = (np.ones(shape=[mc.M//n,mc.radix,n]) * w).transpose([0,2,1]).reshape([-1,mc.radix])[perm]
    W = np.r_[W, w_4_x]
    n *= mc.radix

fa = True
Wp = 0

for k in range(mc.depth):
    for i in range(mc.L):
        a, b = divmod(i, mc.radix**(k-1))
        ix = [b + a*4**k + j*4**(k-1) for j in range(mc.radix)]
        for rot in range(mc.radix):
            if fa:
                ix = [perm[i*4 + rot]]*4
            fft4x(*[s[(rot+j) % mc.radix] for j in range(mc.radix)],
                  *ix,
                  *W[Wp])
            Wp += 1
    if fa:
        fa = False

In [217]:
abs(mc.unmix(s) - np.fft.fft(x)).max()

7.577671997283021e-06

In [187]:
def comp_idx(i, j, k):
    a, b = divmod(i, 4**k)
    return b + a*4**(k+1) + j*4**k