In [1]:
from fftw import generate_fft, default_config
import numpy as np

In [3]:
default_config["generator_path"] = "../genfft"
default_config["compile_args"] = ["-x", "c++", "-O3", "-include", "fftw/codelet.hh", "-shared"]
fft5 = generate_fft(default_config, "notw", n=5)

In [5]:
x = np.arange(5, dtype='complex64')

In [6]:
y = np.zeros_like(x)

In [7]:
fft5(x, y)

In [8]:
y

array([10. +0.j       , -2.5+3.440955j , -2.5+0.8122992j, -2.5-0.8122992j,
       -2.5-3.440955j ], dtype=complex64)

In [39]:
fft16 = generate_fft(default_config, "notw", n=16)
fft4 = generate_fft(default_config, "notw", n=4)
fft2 = generate_fft(default_config, "notw", n=2)

In [40]:
x = np.arange(16, dtype='complex64')
y = np.zeros_like(x)

In [56]:
def w(k, n):
    return np.exp(-2j * np.pi * k / n)


def fft_p2(x):
    y = np.zeros_like(x)
    n = x.size
    if n == 1:
        return x
#         fft2(x, y)
#     elif n == 4:
#         fft4(x, y)
    else:
        a = fft_p2(x[::2])
        b = fft_p2(x[1::2])
        c = w(np.arange(n//2, dtype='float32'), n)
        y[n//2:] = a + c * b
        y[:n//2] = a - c * b
        
    return y

In [57]:
fft_p2(x)

array([  0.        +0.j      ,  -5.071597  -6.975129j,
         6.6274166-16.j      ,  38.91514  +20.153154j,
         0.        +0.j      ,  22.339705 +63.466866j,
       -38.627415 +16.j      , -24.183239 -27.661419j,
         0.        +0.j      , -24.183239 +27.661423j,
       -38.62742  -16.j      ,  22.339697 -63.466866j,
         0.        +0.j      ,  38.91513  -20.15316j ,
         6.6274157+15.999999j,  -5.0715933 +6.975128j], dtype=complex64)

In [43]:
fft16(x, y)

In [44]:
y

array([120. +0.j       ,  -8.+40.218716j ,  -8.+19.31371j  ,
        -8.+11.972846j ,  -8. +8.j       ,  -8. +5.3454294j,
        -8. +3.3137083j,  -8. +1.5912971j,  -8. +0.j       ,
        -8. -1.5912971j,  -8. -3.3137083j,  -8. -5.3454294j,
        -8. -8.j       ,  -8.-11.972846j ,  -8.-19.31371j  ,
        -8.-40.218716j ], dtype=complex64)