In [2]:
from fftw import generate_fft, default_config
import numpy as np

In [3]:
default_config["generator_path"] = "../genfft"
default_config["compile_args"] = ["-x", "c++", "-O3", "-include", "fftw/codelet.hh", "-shared"]
fft5 = generate_fft(default_config, "notw", n=5)

In [4]:
x = np.arange(5, dtype='complex64')

In [5]:
y = np.zeros_like(x)

In [6]:
fft5(x, y)

In [7]:
y

array([10. +0.j       , -2.5+3.440955j , -2.5+0.8122992j, -2.5-0.8122992j,
       -2.5-3.440955j ], dtype=complex64)

In [8]:
fft16 = generate_fft(default_config, "notw", n=16)
fft4 = generate_fft(default_config, "notw", n=4)
fft2 = generate_fft(default_config, "notw", n=2)
twiddle4 = generate_fft(default_config, "twiddle", n=4)

In [9]:
x = np.arange(16, dtype='complex64')
y = np.zeros_like(x)

In [16]:
def w(k, n):
    return np.exp(-2j * np.pi * k / n)


def fft_p16(x):
    yA = np.zeros_like(x).reshape([4,4])
    yB = yA.T
    z = np.zeros_like(x)
    fft4(x.reshape([4,4]).T, yA)
    I = np.arange(4)
    yA *= w(I[:,None]*I[None,:], 16)
    fft4(yB, z.reshape([4,4]).T)
    return z


def fft_t16(x):
    yA = np.zeros_like(x).reshape([4,4])
    yB = yA.T
    z = np.zeros_like(x)
    fft4(x.reshape([4,4]).T, yA)
    I = np.arange(4)
    twiddle = w(I[:,None]*I[None,1:], 16).astype('complex64')
    # print(yA, twiddle, yA.strides, yB.strides)
    twiddle4(yB, twiddle)
    return y.flatten()

In [17]:
fft_p16(x)

array([120. +0.j       ,  -8.+40.21872j  ,  -8.+19.31371j  ,
        -8.+11.972846j ,  -8. +8.j       ,  -8. +5.3454294j,
        -8. +3.3137083j,  -8. +1.591299j ,  -8. +0.j       ,
        -8. -1.591299j ,  -8. -3.3137083j,  -8. -5.3454294j,
        -8. -8.j       ,  -8.-11.972846j ,  -8.-19.31371j  ,
        -8.-40.21872j  ], dtype=complex64)

In [ ]:
fft_t16(x)

In [15]:
I = np.arange(4)
twiddle = w(I[:,None]*I[None,1:], 16).astype('complex64')

In [ ]:
twiddle4(x.reshape(4,4), twiddle)

In [19]:
x

array([ 6.+0.j, -2.+2.j, -2.+0.j, -2.-2.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j], dtype=complex64)